### ISSUE TITLE
access to documentation is denied

### ISSUE THREAD

**Issue by Cejkis-zz** [tadams42/sokoenginepy#1]
Hey, links for API and tutorial in readme don't work, my permission is denied.

**Comment by tadams42** [comment]
Hmmm, strange but true... I'll fix them later, for now you can use these:

Tutorial: http://sokoenginepy.readthedocs.io/en/latest/tutorial.html
API docs: http://sokoenginepy.readthedocs.io/en/latest/api.html

**Comment by tadams42** [comment]
Fixed in deb1d3aabf34ef2360404a82583fae1d06205a2b
